config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :attendances
  resources :events
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :information_send

  belongs_to :guest, class_name: 'User'

  belongs_to :attended_event, class_name: 'Event'

  validates :stripe_customer_id,
  presence: true,
  uniqueness: true

  private

  # sending notification email to event creator
  def information_send
    AttendanceMailer.new_guest_email(self.attended_event.host).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord
	
	belongs_to :host, class_name: 'User'

	has_many :attendances, foreign_key: 'attended_event_id'

	has_many :guests, through: :attendances, source: :guest

	validates :start_date, presence: true, date: { after_or_equal_to: Proc.new { Date.today }, message: "must be at least #{(Date.today).to_s}" }, on: :create

	validates :duration, presence: true

	validates :title, 
		presence: true,
		length: {in: 5..140, message: "length must be between 5 and 140 characters long"}

	validates :description, 
		presence: true,
		length: {in: 20..1000, message: "length must be between 20 and 1 000 characters long"}

	validates :price, 
		presence: true,
		numericality: { only_integer: true, greater_than: 1, less_than: 1000 }

	validates :location, presence: true

	validate :duration_must_be_multiple_of_5

	private

# custom validator for duration
  def duration_must_be_multiple_of_5
    errors.add(:duration, 'must be a multiple of 5') if
    duration%5 != 0
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	after_create :welcome_send

  has_many :hosted_events, class_name: 'Event', foreign_key: 'host_id'

  has_many :attendances, foreign_key: 'guest_id'

  has_many :attended_events, through: :attendances, source: :attended_event

  private

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: :new

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(
      'start_date' => params[:start_date],
      'duration' => params[:duration],
      'title' => params[:title],
      'description' => params[:description],
      'price' => params[:price],
      'location' => params[:location],
      'host_id' => current_user.id)
    if @event.save
      redirect_to event_path(current_user.hosted_events.last)
    else
      render 'new'
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      flash.now[:danger] = 'Event could not be updated - please check your input.'
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :start_date, :duration, :description, :price, :location)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :is_creator?

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id]) 
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to event_path, notice: 'User was successfully created.'
    else
      flash[:danger] = 'Something went wrong - please check your input'
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      flash[:danger] = 'Something went wrong - please check your input'
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :description)
    end

    def is_creator?
      @user = User.find(params[:id])
      unless @user.id == current_user.id
      flash[:danger] = "This is not your account"
      redirect_to user_path(current_user)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_controller_helper.rb
module EventsControllerHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
 <!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron" style="background-image: url('/jumbotron_img.jpeg');">
  <div class="container">
	  <h1 class="display-3">Hello, world!</h1>
	  <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
	  <p> <%= link_to "Your event", new_event_path, :class =>'btn btn-primary btn-lg' %> </p>
	</div>
</div>

<div class='container-fluid'>
	<div class ='row px-2 justify-content-around'>
		<% @events.each do |event| %>
		  <div class ="card col-10 col-md-5 col-lg-3 mx-1 my-3 border-primary">
				<img class="card-img-top" src="<%= rand(1..5) %>.jpeg" alt="Card image cap">
				<div class="card-body">
				  <h3><%= event.title %></h3>
				  <p><%= event.start_date %></p>
				  <p><%= event.description %></p>
				  <h4><%= event.location %></h4>
          <span class="btn btn-secondary" role="button"> <%= link_to "To see more", event_path(event.id.to_s), style: 'color:#000000;', class: 'css_class' %> </span>
			  </div>
			</div>
		<% end %>	
	</div>
</div>

app/views/events/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Create your event</title>
</head><body class="bg-light">  <div class="container">
    <div class="py-5 text-center">
    </br>
    <h2>Create your event</h2>
    <p class="lead">Whatever you want anywhere anytime</p>
  </div>  <div class="col-md-12 order-md-1">
    <h4 class="mb-3">Start date</h4>    
    <%= form_tag url_for(action: 'create'), method: "post" do %>
    <div class="row">
      <div class="col-md-6 mb-3">
        <%= label_tag 'Start date' %><br />
        <%= text_field_tag 'start_date', @event.start_date, :class => 'form-control', placeholder: '2019-11-05 22:30:20' %> 
      </div>
      <div class="col-md-6 mb-3">
        <%= label_tag 'Duration' %><br />
        <%= text_field_tag 'duration', @event.duration, :class => 'form-control', placeholder: '60' %>
      </div>
    </div> 
    <div class="row">
      <div class="col-md-6 mb-3">
        <%= label_tag 'Title' %><br />
        <%= text_field_tag 'title', @event.title, :class => 'form-control', placeholder: '43' %>
      </div>
    </div>    <div class="mb-3">
      <%= label_tag 'Description' %><br />
      <%= text_field_tag 'description', @event.description, :class => 'form-control', placeholder: 'Jeune cadre dynamique avide de potins croustillants' %>
    </div>    <div class="row">
      <div class="col-md-6 mb-3">
        <%= label_tag 'Price' %><br />
        <%= text_field_tag 'price', @event.price, :class => 'form-control', placeholder: 'gael.dubois@gmail.com' %>
      </div>
      <div class="col-md-6 mb-3">
        <%= label_tag 'Location' %><br />
        <%= text_field_tag 'location', @event.location, :class => 'form-control', placeholder: 'password' %>
      </div>
    </div>  </br> <%= submit_tag "S'inscrire", :class => 'btn btn-primary btn-lg btn-block' %>  <% end %> <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; The Gossip Project</p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Privacy</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Support</a></li>
    </ul>
  </footer></body>
</html>

app/views/events/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Event</title>
</head>
<body>

	</br></br></br>
	<div class="card text-center">
		<div class="card-header"><%= @event.title %></div>
		<div class="card-body">
			<h5 class="card-title"><%= @event.description %></h5>
			<p class="card-text"><%= @event.start_date %></p>
			<p class="card-text"><%= @event.location %></p>
			<p class="card-text"><%= @event.price %></p>
		</div>
	</div>
	
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Eventbrite Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="app/assets/stylesheets/application.css">
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  </head>

  <body>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">


      <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Home", events_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <%unless current_user %>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link", style: 'color:#FFFFFF' %>
          </li>
          <li class="nav-item">
              <%= link_to "Sign In", new_user_registration_path, class: "nav-link", style: 'color:#FFFFFF' %>
          </li>
          <% end %>
        </ul>
      </div>
      <%if current_user %>
          <%= link_to "Create", new_event_path, class: "navbar-brand" %>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Nav Options
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to "My profil", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>  
      <% end %>
    </nav>
  

      <!-- Alert status -->
    <% if flash[:success] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:success] %>
      </div>
    <%elsif flash[:danger] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:danger] %>
      </div>
    <% end %>


    <%= yield %>

  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
	<head>
		<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
		<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<!------ Include the above in your HEAD tag ---------->
		<title>My profile</title>
	</head>
	<body>	
		<div class="container">
			<div class="row">
				<div class="col-md-6 img">
					<p><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvzOpl3-kqfNbPcA_u_qEZcSuvu5Je4Ce_FkTMMjxhB-J1wWin-Q"  alt="" class="img-rounded"></p>
					<p><%= link_to "edit profile", edit_user_registration_path, class: "btn btn-primary" %></p>
				</div>
				<div class="col-md-6 details">
					<blockquote>
						<h3><%= @user.first_name %> <%= @user.last_name %></h3>
					</blockquote>
					<p>Description :<br>
						"<%= @user.description %>"
					</p>
					<p>Email :<br>
						<%= @user.email %>
					</p>
					<p>Membre depuis le :<br>
						<%= @user.created_at %>
					</p>
					<p>Profil mis à jour le :<br>
						<%= @user.updated_at %>
					</p>
				</div>
			</div>
		</div>

		<hr>

		<div class='container-fluid'>
		<h4 class='text-primary'>Events of <%= @user.first_name %> <%= @user.last_name %> :</h4>
		<!-- Example row of columns -->
		<div class ='row px-2 justify-content-around'>
			<% @user.hosted_events.each do |hosted_event| %>
			<div class ="card col-10 col-md-5 col-lg-3 mx-1 my-3 border-primary">
				<div class="card-body">
					<h2><%= hosted_event.title %></h2>
					<p><%= link_to "More details", event_path(hosted_event.id.to_s), class: "btn btn-primary" %></p>
				</div>
			</div>
			<% end %>
		</div>
		<hr>
	</div> <!-- /container -->





	</body>
</html>